services:
  - type: web
    name: leetcode-stats-dashboard
    env: python
    region: india
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app.main:app"
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: HOD_PASSWORD
        value: your-secure-password-here
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
